version: '3'

services:
  php:
    build: ..
    ports:
      - "8082:80"
      - "443:443"
    volumes:
      - ..:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "admin"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge